version: '2.3'
services:
         
  flask:
    build: 
        context: ./docker
        dockerfile: Dockerfile.flask
    hostname: flask
    container_name: flask
    volumes:
      - .:/project
    stdin_open: true
    expose:
      - "5000"
    ports:
      - "5000:5000"
    tty: true
    command: python3 project/maxrebo/maxrebo.py

  bert:
    build:
        context: ./docker
        dockerfile: Dockerfile.bert
    hostname: bert
    container_name: bert
    privileged: true
    ports:
        - "8888:8888"
    # runtime: nvidia
    # command: bash
    tty: true
    stdin_open: true
    volumes: 
      - .:/project
      - ./model:/model

