version: '2'
services:
         
  flask:
    build: 
        context: ./docker
        dockerfile: Dockerfile.flask
    hostname: flask
    container_name: flask
    volumes:
      - .:/project
    stdin_open: true
    expose:
      - "5000"
    ports:
      - "5000:5000"
    tty: true
    command: python3 project/maxrebo/maxrebo.py

  bert:
    build:
        context: ./docker
        dockerfile: Dockerfile.bert
    hostname: pyspark
    container_name: pyspark
    privileged: true
    ports:
        - "5555:5555"
        - "5556:5556"
    runtime: nvidia
    command: bash -c "bert-as-service 1"
    # command: bash
    tty: true
    stdin_open: true
    volumes: 
      - .:/project
      - ./model:/model

