# FROM tensorflow/tensorflow:latest-gpu-jupyter
FROM tensorflow/tensorflow:1.12.0-devel-gpu-py3
# RUN pip install bert-serving-server
RUN pip install pandas
# COPY ./docker/entrypoint.sh /app
# WORKDIR /app
# ENTRYPOINT ["/app/entrypoint.sh"]
# CMD []